name: LearningToolsXcodegen
options:
  bundleIdPrefix: com.saurabh
  deploymentTarget:
    iOS: "26.0"
  developmentLanguage: en
  xcodeVersion: "16.0"
  usesTabs: false
  indentWidth: 4
  tabWidth: 4

packages:
  Alamofire:
    url: https://github.com/Alamofire/Alamofire.git
    from: 5.9.0

targets:
  LearningToolsXcodegen:
    type: application
    platform: iOS
    deploymentTarget: "26.0"
    sources:
      - path: LearningToolsXcodegen
    dependencies:
      - package: Alamofire
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.saurabh.LearningToolsXcodegen
      MARKETING_VERSION: "1.0"
      CURRENT_PROJECT_VERSION: "1"
      SWIFT_VERSION: "5.0"
      TARGETED_DEVICE_FAMILY: "1,2" # iPhone and iPad
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
      GENERATE_INFOPLIST_FILE: true
      ENABLE_PREVIEWS: true
      INFOPLIST_KEY_UIApplicationSceneManifest_Generation: true
      INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: true
      INFOPLIST_KEY_UILaunchScreen_Generation: true
      INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
      INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
      CODE_SIGN_STYLE: Automatic
      SWIFT_APPROACHABLE_CONCURRENCY: true
      SWIFT_DEFAULT_ACTOR_ISOLATION: MainActor
      SWIFT_EMIT_LOC_STRINGS: true
      SWIFT_UPCOMING_FEATURE_MEMBER_IMPORT_VISIBILITY: true
      STRING_CATALOG_GENERATE_SYMBOLS: true

  LearningToolsXcodegenTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "26.0"
    sources:
      - path: LearningToolsXcodegenTests
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.saurabh.LearningToolsXcodegenTests
      MARKETING_VERSION: "1.0"
      CURRENT_PROJECT_VERSION: "1"
      SWIFT_VERSION: "5.0"
      TARGETED_DEVICE_FAMILY: "1,2"
      GENERATE_INFOPLIST_FILE: true
      CODE_SIGN_STYLE: Automatic
      SWIFT_APPROACHABLE_CONCURRENCY: true
      SWIFT_EMIT_LOC_STRINGS: false
      SWIFT_UPCOMING_FEATURE_MEMBER_IMPORT_VISIBILITY: true
      STRING_CATALOG_GENERATE_SYMBOLS: false
      TEST_HOST: "$(BUILT_PRODUCTS_DIR)/LearningToolsXcodegen.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/LearningToolsXcodegen"
      BUNDLE_LOADER: "$(TEST_HOST)"
    dependencies:
      - target: LearningToolsXcodegen

  LearningToolsXcodegenUITests:
    type: bundle.ui-testing
    platform: iOS
    deploymentTarget: "26.0"
    sources:
      - path: LearningToolsXcodegenUITests
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.saurabh.LearningToolsXcodegenUITests
      MARKETING_VERSION: "1.0"
      CURRENT_PROJECT_VERSION: "1"
      SWIFT_VERSION: "5.0"
      TARGETED_DEVICE_FAMILY: "1,2"
      GENERATE_INFOPLIST_FILE: true
      CODE_SIGN_STYLE: Automatic
      SWIFT_APPROACHABLE_CONCURRENCY: true
      SWIFT_EMIT_LOC_STRINGS: false
      SWIFT_UPCOMING_FEATURE_MEMBER_IMPORT_VISIBILITY: true
      STRING_CATALOG_GENERATE_SYMBOLS: false
      TEST_TARGET_NAME: LearningToolsXcodegen
    dependencies:
      - target: LearningToolsXcodegen

schemes:
  LearningToolsXcodegen:
    build:
      targets:
        LearningToolsXcodegen: all
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - LearningToolsXcodegenTests
        - LearningToolsXcodegenUITests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
  
  LearningToolsXcodegen-Debug:
    build:
      targets:
        LearningToolsXcodegen: all
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - LearningToolsXcodegenTests
        - LearningToolsXcodegenUITests
    profile:
      config: Debug
    analyze:
      config: Debug
    archive:
      config: Debug